import fs from 'fs-extra';
import path from 'path';


const OUT_DIR = path.resolve(import.meta.dirname, 'out');
const DIST_DIR = path.resolve(import.meta.dirname, 'dist');
const BROADCAST_DIR = path.resolve(import.meta.dirname, 'broadcast');



async function build_deployments() {
  // Read all needed ABIs (deduplicated by contract name)
  const abiByContract = {};
  for (const filename of ["IERC8270.sol", "Deposits.sol", "DepositsGno.sol"]) {
    const name = path.basename(filename, path.extname(filename));
  const abiPath = path.join(OUT_DIR, filename, `${name}.json`);
    abiByContract[name] = (await fs.readJson(abiPath)).abi;
  }

  // Read deployed addresses from broadcast files
  const deployments = {};
  for (const chainId of await fs.readdir(path.join(BROADCAST_DIR, 'Deploy.s.sol'))) {
	  const deployment = {};
      const broadcastPath = path.join(BROADCAST_DIR, 'Deploy.s.sol', chainId, 'run-latest.json');
    if (!await fs.pathExists(broadcastPath)) {
      console.log(`Malformed deployment found for ${chainId}`);
      continue;
    }
    const broadcastData = await fs.readJson(broadcastPath);

	  for (const tx of broadcastData.transactions) {
      if (tx.transactionType === 'CREATE' || tx.transactionType === 'CREATE2') {
	      deployment[tx.contractName] = tx.contractAddress;
      }
    }
	  deployments[+chainId] = deployment;
  }

  // Generate JS module
  let js = '// Auto-generated by generate.mjs\n\n';

  // Export each ABI as a named constant
  for (const [name, abi] of Object.entries(abiByContract)) {
    js += `export const ${name}ABI = ${JSON.stringify(abi)};\n\n`;
  }

  // Export the deployments mapping
  js += `export const deployments = ${JSON.stringify(deployments)}\n`;

  await fs.writeFile(path.join(DIST_DIR, 'index.js'), js);

  console.log(`\nGenerated dist/index.js with ${Object.keys(deployments).length} networks`);
}

async function build() {
	await fs.remove(DIST_DIR);
	await fs.ensureDir(DIST_DIR);

	await build_deployments();
}

build().catch(err => {
	console.error('Error:', err);
	process.exit(1);
});
