[default]
check: check-fmt test check-snapshot

alias ck := check

fmt:
    uvx mamushi -l 100 src/**/*.vy src/interfaces/*.vyi
    forge fmt

check-fmt:
    uvx mamushi -l 100 --check src/**/*.vy src/interfaces/*.vyi
    forge fmt --check

test:
    forge test

snapshot:
    forge snapshot

check-snapshot:
    forge snapshot --check

# find a CREATE2 salt for the ERC vanity address
create2:
    cast create2 -e 08270 -i `dependencies/ercs-unversioned/assets/erc-8270/prepare.py | jq -r .initcode`
    
verify: (_verify "560048") (_verify "10200") (_verify "100")
_verify chainid:
	#!/usr/bin/env bash
	set -euo pipefail
	function _sourcify {
		address=$1
		contract_id=$2
		jq '{"compilerVersion": "v0.4.3+commit.bff19ea2", "contractIdentifier": "'$contract_id'", "stdJsonInput": .}' | curl --data @- -H 'Content-Type: application/json' "https://sourcify.dev/server/v2/verify/{{chainid}}/$address"
	}
	vyper -f solc_json dependencies/ercs-unversioned/assets/erc-8270/ERC8270.vy | _sourcify `jq -r .transactions[0].contractAddress broadcast/Deploy.s.sol/{{chainid}}/run-latest.json` dependencies/ercs-unversioned/assets/erc-8270/ERC8270.vy:ERC8270
	vyper -f solc_json dependencies/ercs-unversioned/assets/erc-8270/WithdrawalReceiver.vy | _sourcify `jq -r .transactions[0].additionalContracts[0].address broadcast/Deploy.s.sol/{{chainid}}/run-latest.json` dependencies/ercs-unversioned/assets/erc-8270/WithdrawalReceiver.vy:WithdrawalReceiver
